spring.application.name=todos-api

spring.datasource.url=jdbc:mysql://localhost:3306/todos_db
spring.datasource.username=root
spring.datasource.password=qw-3142676

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true